# Example YAML configuration for TARDIS
tardis_config_version: v1.0

supernova:
  luminosity_requested: 1.e42 erg/s
  # luminosity_wavelength_start: 3000 angstrom
  # luminosity_wavelength_end: 10000 angstrom
  time_explosion: 5 day

atom_data: kurucz_cd23_chianti_H_He.h5

csvy_model: tardis_example_csvy.csvy   

plasma:
  initial_t_inner: 7000 K
  disable_electron_scattering: no
  ionization: nebular
  excitation: dilute-lte
  radiative_rates_type: dilute-blackbody
  line_interaction_type: downbranch
  helium_treatment: recomb-nlte

montecarlo:
  seed: 23111963
  no_of_packets: 5e4
  iterations: 50
  nthreads: 1  # increase threads number to speed up the simulation if hardware supports it
  last_no_of_packets: 1e6
  no_of_virtual_packets: 0

  convergence_strategy:
    type: damped
    damping_constant: 0.5
    threshold: 0.05
    # w:
    #   threshold: 0.08 # increase the threshold to speed up convergence for SESN
    fraction: 0.8
    hold_iterations: 5
    stop_if_converged: True
    t_inner:
      damping_constant: 0.5 # keep t_inner an constant if set to 0.0
    v_inner_boundary:     # v_inner_workflow convergence strategy
      damping_constant: 0.5
      threshold: 0.01
      type: damped


spectrum:
  start: 2000 angstrom
  stop: 25000 angstrom
  num: 5000
  integrated:
    interpolate_shells: 100
  #   compute: GPU